### ISSUE TITLE
Ubuntu 24.04 Support

### ISSUE THREAD

**Issue by danielstojkovski** [scalyr/scalyr-agent-2#1261]
Hello,
I am using the install instructions from here: https://app.scalyr.com/help/install-agent-linux?teamToken=zKjoHZMakitVemhyJ1xvXQ--
inside a docker image. When I use ubuntu:24.04, I get the following:

`Adding the scalyr agent repository.
Update scalyr repository.
  Installing scalyr-agent-2 package
Install failed while executing "apt-get -y install scalyr-agent-2".  Execute "apt-get -y install scalyr-agent-2" to see error.

Displaying last 20 lines from scalyr_install.log

...
+ command python3 [3.12.3] is found and matches the minimum required version - Success!
+ The Scalyr Agent will use the default system python3 binary (/usr/bin/env python3).
Traceback (most recent call last):
  File "/usr/share/scalyr-agent-2/bin/scalyr-agent-2", line 95, in <module>
    import scalyr_agent.scalyr_logging as scalyr_logging
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/__init__.py", line 60, in <module>
    from scalyr_agent.scalyr_monitor import ScalyrMonitor
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/scalyr_monitor.py", line 42, in <module>
    import scalyr_agent.scalyr_logging as scalyr_logging
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/scalyr_logging.py", line 51, in <module>
    import scalyr_agent.util as util
  File "/usr/share/scalyr-agent-2/py/scalyr_agent/util.py", line 54, in <module>
    import six.moves._thread
ModuleNotFoundError: No module named 'six.moves'
/usr/bin/env: 'python': No such file or directory
dpkg: error processing package scalyr-agent-2 (--configure):
 installed scalyr-agent-2 package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 scalyr-agent-2
E: Sub-process /usr/bin/dpkg returned an error code (1)

See scalyr_install.log for additional details.
The command '/bin/sh -c bash ./install-agent.sh --set-api-key 0xJ6z1ov6Wtz8I7x9IxhYPJa88XerYd49JiSf1N4a18U-' returned a non-zero code: 1`

I tried building the same docker image with ubuntu:22.04 base and it worked fine. However when I used the image on an ubuntu:24.04 based device I encountered a journal file incompatibility, and I couldn't see logs in scalyr- this is a second order issue, I am sure when I can install scalyr on an ubuntu:24.04 base image everything will be fine :)

**Comment by oleg-s1** [comment]
@danielstojkovski 
We are working on adding support for Ubuntu 24.04 for scalyr-agent

Meanwhile could you, please, try AIO package?
```
sudo apt-get update
sudo apt-get remove scalyr-agent-2
sudo apt-get install scalyr-agent-2-aio
```
This package contains all necessary libraries and packages as bundle.

**Comment by wynnw** [comment]
Still happening in Oct. 2025...the scalyr-agent-2-aio package did work.

**Comment by danielstojkovski** [comment]
Ok, so I got this working using:

```
curl -sO https://www.scalyr.com/install-agent.sh
chmod +x install-agent.sh
./install-agent.sh --use-aio-package
```

This will install scalyr-agent-2 and the 'six.moves' issue above is fixed :) You will most likely need to use the --set-api-key option as well (I don't because I am docker-izing scalyr, I set the key somewhere else).

For my purposes, I am using the journald monitor, so I also needed to:

```
/opt/scalyr-agent-2/python3/bin/python3 -m pip install --upgrade pip
/opt/scalyr-agent-2/python3/bin/python3 -m pip install systemd-python
export PYTHONPATH=$PYTHONPATH:/opt/scalyr-agent-2/python3/lib/python3.11/site-packages
```

I then put my scalyr config files in the /etc/scalyr-agent-2 directory. Finally, scalyr-agent-2 start
